apiVersion: apps/v1
kind: Deployment

metadata:
  name: trading-app
  namespace: trading-app

spec:
    replicas: 1

    selector:
        matchLabels:
            app: trading-app

    template:
      metadata:
        labels:
          app: trading-app

      spec:
        imagePullSecrets:
          - name : ghcr-secret
        containers:
            - name: trading-app
              image: ghcr.io/somu-freewheel/trading-app:5ca3375fd96b0dc80ab56633333b2bd3e8ab3f75
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080

              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:postgresql://postgres-service:5432/trading_db
                - name: SPRING_DATASOURCE_USERNAME
                  value: postgres
                - name: SPRING_DATASOURCE_PASSWORD
                  value: user123
                - name: SPRING_REDIS_HOST
                  value: redis-service
                - name: SPRING_REDIS_PORT
                  value: "6379"



