apiVersion: apps/v1
kind: Deployment

metadata:
  name: trading-app
  namespace: trading-app

spec:
    replicas: 1

    selector:
        matchLabels:
            app: trading-app

    template:
      metadata:
        labels:
          app: trading-app

      spec:
        containers:
            - name: trading-app
              image: your-docker-registry/trading-app:v1
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080

              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:postgresql://postgres-service:5432/trading_db
                - name: SPRING_DATASOURCE_USERNAME
                  value: postgres
                - name: SPRING_DATASOURCE_PASSWORD
                  value: user123
                - name: SPRING_REDIS_HOST
                  value: redis-service
                - name: SPRING_REDIS_PORT
                  value: "6379"



