apiVersion: v1
kind: Service

metadata:
  name: trading-app-service
  namespace: trading-app

spec:
  selector:
    app: trading-app

  ports:
    - port: 8080 #local host and container live host will  be different 
      targetPort: 8080

  type: NodePort #Load Balancer
